### PR TITLE
Reorder get_sender bots vs user checks

### PR DESCRIPTION
**Pull request by luk1337**
* Fixes display names for 'app' users,
  in before it'd be displayed as "bot :]"
  and now it's "-{display name}-".

### CODE REVIEW

**Comment by tfheen** [comment]
This breaks displaying of bots as bots, so I don't think this is something we want to merge as is. It should already be rendered as `DisplayName :]` (that is, display name with spaces removed + bot marker.)  Are you not seeing that?

**Comment by luk1337** [comment]
It's rendered as "bot :]" here:
image

**Comment by tfheen** [comment]
Can you provide the JSON for one of those messages and the user? 

Doing `/set plugins.var.python.slack.record_events "true"` and then `/python reload slack` and navigating to the channel it's talking in should be enough. The JSON will be in `/tmp/weeslack-debug`. (Make sure to set `record_events` back to false afterwards. :-) )

**Comment by luk1337** [comment]
```
{  
   "username":"luca020400",
   "icons":{  
      "image_48":"https://slack-files2.s3-us-west-2.amazonaws.com/bot_icons/2018-03-09/326784926737_48.png"
   },
   "text":"Well no docs, it's helpful",
   "ts":"1520602371.000444",
   "subtype":"bot_message",
   "type":"message",
   "bot_id":"B9LJZ5N65"
},
```

**Comment by tfheen** [comment]
Can you provide the user information for `bot_id: B9LJZ5N65`? It might be in the rtmstart information.

**Comment by luk1337** [comment]
```
{
   "updated": 1520576133,
   "name": "bot",
   "icons": {
       "image_36": "https://a.slack-edge.com/7f1a0/plugins/bot/assets/service_36.png",
       "image_48": "https://a.slack-edge.com/7f1a0/plugins/bot/assets/service_48.png",
       "image_72": "https://a.slack-edge.com/7f1a0/plugins/bot/assets/service_72.png"
   },
   "deleted": false,
   "app_id": "A0F7YS25R",
   "id": "B9LJZ5N65"
}
```

**Comment by tfheen** [comment]
Can you try out https://err.no/p/2018-03-09-DiPKftBex7s/stdin and see if you're ok with that too? It seems to work for me, at least.

**Comment by luk1337** [comment]
Seems to work here:
image

**Comment by tfheen** [comment]
Great, thanks for the feeback. I'll merge yours and then drop my changes on top to clean up a little bit and keep formatting of bot messages as such.

**Pull request merged**
