### PR TITLE
Reply to existing thread with a command

### PR DESCRIPTION
**Pull request by janza**
This allows for replying in threads existing threads using command:

```
/thread b4d Hello thread!
```

Useful with the feature to show thread messages in the parent channel, see #616

### CODE REVIEW

**Comment by trygveaa** [comment]
I think it makes more sense to use the `/reply` command instead of the `/thread` command for this. I.e. change the `/reply` command to allow a thread hash in addition to a number.

**Comment by yeled** [comment]
Why don't /thread or /reply tab complete?

**Comment by janza** [comment]
I'll try to change it. It might be tricky distinguishing between hashes (which might be just numbers) and line numbers.

**Comment by trygveaa** [comment]
We can probably assume no one is going to count 100 messages back, so everything with three characters or more can be assumed to be a hash.

**Comment by trygveaa** [comment]
@yeled: `/reply` currently only accepts numbers, so it's nothing to complete. `/thread` could probably complete message hashes, it's just not implemented by anyone. Actually, I don't think we have completion for any other commands than `/slack` (and the options for that command are static).

**Comment by janza** [comment]
Ah, cool! then I'll close this one.

**Pull request closed without merging**
