### PR TITLE
Format python files with black

### PR DESCRIPTION
**Pull request by sudoforge**

### CODE REVIEW

**Comment by sudoforge** [comment]
@trygveaa per [your comment](https://github.com/wee-slack/wee-slack/pull/816#issuecomment-791921311), here's a PR adding `black` (and formatting all current files). This is done in two separate commits.

**Comment by trygveaa** [comment]
Thanks! Since the checks in this PR were failing, I ran black myself and committed to master. Turns out the code hit a bug in black, so we had to run it twice, see https://github.com/psf/black/issues/2055.

**Comment by sudoforge** [comment]
Oof, sorry, I should have added a comment here but got caught up in other things. There actually appears to be an error on subsequent formatting (with python < 3), which is why the checks are failing.

I did run with `--fast` in order to format `wee_slack.py` in the commit present in this PR. That wasn't the issue here.

**Comment by sudoforge** [comment]
🤷‍♂️ it appears to work for you now, at least on `HEAD`... if you find spurious CI failures on the lint check, I'd recommend removing it until you hear back on the issue you opened and have a solution.

**Comment by trygveaa** [comment]
How do you figure the issue is with python < 3? The checks were failing for all python versions.

As I said, I had to run black twice, because running with `black --fast` made a file that still wasn't formatted properly (which is why we had to use `--fast`). You can see there's a diff between this PR and what I committed. The bug in black is with the particular formatting we used, so after formatting it twice it's now formatted properly and works correctly.

**Comment by sudoforge** [comment]
When running locally on this tree, I am not able to recreate your experience with 3.9.2:

```
(wee-slack) gh::sudoforge/wee-slack [ 2e42e72 ]
➜ git rev-parse HEAD
2e42e72c96aa2f5dc5b51df50598324c12f2a1a9

^-- this commit is _before_ any files have been formatted (it is the commit that adds black to the deps)


(wee-slack) gh::sudoforge/wee-slack [ e5bafdd ]
➜ python -V
Python 3.9.2


(wee-slack) gh::sudoforge/wee-slack [ 2e42e72 ]
➜ black --fast wee_slack.py
reformatted wee_slack.py
All done! ✨ 🍰 ✨
1 file reformatted.


(wee-slack) gh::sudoforge/wee-slack [ 2e42e72 ~1 ]
➜ black .
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_everything.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_eventrouter.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_formatting.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_presencechange.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_processsubteamcreated.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_command_reply.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_processreply.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_processteamjoin.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_processsubteamupdated.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_sendmessage.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_process_message.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_linkifytext.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_thread.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/generate_docs.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/generate_weemoji.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_topic_command.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/conftest.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_utf8_helpers.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_unfurl.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_formatted_name.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_unwrap_attachments.py
All done! ✨ 🍰 ✨
21 files reformatted, 2 files left unchanged.


(wee-slack) gh::sudoforge/wee-slack [ 2e42e72 ~22 ]
➜ git commit -am 'all files have now been formatted for the first time'
[detached HEAD e5bafdd] all files have now been formatted, once
 22 files changed, 3237 insertions(+), 1955 deletions(-)
 rewrite _pytest/test_formatted_name.py (94%)
 rewrite _pytest/test_linkifytext.py (67%)
 rewrite _pytest/test_unfurl.py (95%)
 rewrite _pytest/test_unwrap_attachments.py (98%)


(wee-slack) gh::sudoforge/wee-slack [ e5bafdd ]
➜ black .
All done! ✨ 🍰 ✨
23 files left unchanged.
```

That's where my statement comes from. Perhaps I'm incorrect, or missing something obvious. In any case, I'm glad you got it sorted out!

**Comment by sudoforge** [comment]
When running locally on this tree, I am not able to recreate your experience with 3.9.2:

```
(wee-slack) gh::sudoforge/wee-slack [ 2e42e72 ]
➜ git rev-parse HEAD
2e42e72c96aa2f5dc5b51df50598324c12f2a1a9

^-- this commit is _before_ any files have been formatted (it is the commit that adds black to the deps)


(wee-slack) gh::sudoforge/wee-slack [ e5bafdd ]
➜ python -V
Python 3.9.2


(wee-slack) gh::sudoforge/wee-slack [ 2e42e72 ]
➜ black --fast wee_slack.py
reformatted wee_slack.py
All done! ✨ 🍰 ✨
1 file reformatted.


(wee-slack) gh::sudoforge/wee-slack [ 2e42e72 ~1 ]
➜ black .
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_everything.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_eventrouter.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_formatting.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_presencechange.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_processsubteamcreated.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_command_reply.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_processreply.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_processteamjoin.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_processsubteamupdated.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_sendmessage.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_process_message.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_linkifytext.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_thread.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/generate_docs.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/generate_weemoji.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_topic_command.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/conftest.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_utf8_helpers.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_unfurl.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_formatted_name.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_unwrap_attachments.py
All done! ✨ 🍰 ✨
21 files reformatted, 2 files left unchanged.


(wee-slack) gh::sudoforge/wee-slack [ 2e42e72 ~22 ]
➜ git commit -am 'all files have now been formatted for the first time'
[detached HEAD e5bafdd] all files have now been formatted for the first time
 22 files changed, 3237 insertions(+), 1955 deletions(-)
 rewrite _pytest/test_formatted_name.py (94%)
 rewrite _pytest/test_linkifytext.py (67%)
 rewrite _pytest/test_unfurl.py (95%)
 rewrite _pytest/test_unwrap_attachments.py (98%)


(wee-slack) gh::sudoforge/wee-slack [ e5bafdd ]
➜ black .
All done! ✨ 🍰 ✨
23 files left unchanged.
```

That's where my statement comes from. Perhaps I'm incorrect, or missing something obvious. In any case, I'm glad you got it sorted out!

**Comment by sudoforge** [comment]
And just to show that it had nothing to do with the order of operations in my previous comment:

```
(wee-slack) gh::sudoforge/wee-slack [ 2e42e72 ]
➜ black .
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_eventrouter.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_formatting.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_everything.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_command_reply.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_processreply.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_presencechange.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_processsubteamcreated.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_processteamjoin.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_sendmessage.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_processsubteamupdated.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_process_message.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_thread.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_linkifytext.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_topic_command.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/generate_docs.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/generate_weemoji.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/conftest.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_utf8_helpers.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_formatted_name.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_unfurl.py
reformatted /home/sudoforge/code/github.com/sudoforge/wee-slack/_pytest/test_unwrap_attachments.py
error: cannot format /home/sudoforge/code/github.com/sudoforge/wee-slack/wee_slack.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_90y12noh.log
Oh no! 💥 💔 💥
21 files reformatted, 1 file left unchanged, 1 file failed to reformat.
black .  7.72s user 0.17s system 137% cpu 5.733 total


(wee-slack) gh::sudoforge/wee-slack [ 2e42e72 ~21 ]
➜ black --fast wee_slack.py
reformatted wee_slack.py
All done! ✨ 🍰 ✨
1 file reformatted.


(wee-slack) gh::sudoforge/wee-slack [ 2e42e72 ~22 ]
➜ black --fast wee_slack.py


(wee-slack) gh::sudoforge/wee-slack [ 2e42e72 ~22 ]
➜ git commit -am 'all files have now been formatted for the first time'
[detached HEAD df90991] all files have now been formatted for the first time
 22 files changed, 3237 insertions(+), 1955 deletions(-)
 rewrite _pytest/test_formatted_name.py (94%)
 rewrite _pytest/test_linkifytext.py (67%)
 rewrite _pytest/test_unfurl.py (95%)
 rewrite _pytest/test_unwrap_attachments.py (98%)


(wee-slack) gh::sudoforge/wee-slack [ df90991 ]
➜ black .
All done! ✨ 🍰 ✨
23 files left unchanged.
```

**Comment by trygveaa** [comment]
I should have mentioned this, but you need to touch or otherwise change/save the wee_slack.py file before you run black again. If not, black won't do anything when you run it again. I guess it has a cache of the last run time it checks against mtime or something.

**Comment by sudoforge** [comment]
Ah, that's what I was missing, then. Well, glad you got it sorted out -- I'd been deferring digging in to this until I had more time in the next couple of weeks.

**Review by osamashadwo — APPROVED** [review]

**Pull request closed without merging**
