### PR TITLE
Rename to slack.py

### PR DESCRIPTION
**Pull request by tfheen**
This aligns our ducks, and makes `/python load slack.py` and `/python reload slack` more similar.

### CODE REVIEW

**Comment by rawdigits** [comment]
After the pep8 fix merge, this has conflicts. Doh.

**Comment by tfheen** [comment]
Rebased. :-)

**Comment by rawdigits** [comment]
gah - broke merge again.

**Comment by tfheen** [comment]
I'm just going to close this since it can't be usefully done as a PR, we need to close out outstanding PRs (or rebase them afterwards) and just do it in master.

**Pull request closed without merging**
