### PR TITLE
use nick_color_name instead of irc_nick_color_name

### PR DESCRIPTION
**Pull request by bendem**
that removes the dependency on the irc plugin for nick coloring.

### CODE REVIEW

**Comment by devkev** [comment]
If `w.info_get('nick_color_name', self.name)` returns falsy, you should fall back to using `w.info_get('irc_nick_color_name', self.name)`, so that the plugin doesn't break for people on older versions of weechat (pre 1.5 when nick coloring was moved to core).

**Comment by bendem** [comment]
@devkev done

**Comment by bendem** [comment]
Rebased

**Comment by ToxicFrog** [comment]
Now that I've actually had a chance to look at this (sorry for the delay) -- it looks fine as far as it goes, but it only affects `SlackDMChannel` -- there's a similar function in `SlackUser` that needs to be updated as well.

**Comment by bendem** [comment]
Yeah, the change was lost in the rebase due to a conflict with https://github.com/wee-slack/wee-slack/commit/925278f11a5eb137c42b5232714c239fe7e25c3b. Should I add the fallback to `SlackUser` or remove it from `SlackDMChannel`?

**Comment by ToxicFrog** [comment]
Add it to SlackUser, IMO, or factor it out into a common function used by both -- the goal here is to use the new API if available, but cleanly fall back to the old one for people on pre-1.5 weechat.

**Comment by ToxicFrog** [comment]
Obsoleted by #391

**Pull request closed without merging**
