### PR TITLE
switch to GitHub Actions from Travis CI

### PR DESCRIPTION
**Pull request by ashkulz**
Not sure why the run doesn't start here -- it [was successful on my fork](https://github.com/ashkulz/wee-slack/actions/runs/384856868), maybe actions need to be enabled?

### CODE REVIEW

**Comment by trygveaa** [comment]
What's the motivation for this change (or what's the benefits of GitHub Actions over Travis)? I guess that forks can run the tests out of the box too?

> Not sure why the run doesn't start here -- it was successful on my fork, maybe actions need to be enabled?

It probably doesn't run it on PRs until the configuration is in master. I created a branch with it and it ran there: https://github.com/wee-slack/wee-slack/actions/runs/394183048

**Comment by ashkulz** [comment]
When I submitted the other PR, Travis seemed stuck. Considering their announcement about [curtailing the OSS support](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing#building-on-a-public-repositories-only), I thought it'd be good to switch GitHub Actions -- feel free to close this PR if you're not interested :slightly_smiling_face:

**Review by sudoforge — CHANGES_REQUESTED** [review]
I'd recommend splitting the lint and test steps into different jobs so that they can run in parallel, as well as renaming the pipeline file for consistency, and a few other changes. I've included a patch in this comment.

You can copy the following diff to your clipboard, and then apply it with `git apply`:

##### On Linux, with X

```
git apply <(xclip -sel c -o)
```

##### On macOS

```
git apply <(pbpaste)
```

... or whatever the command is for "paste the contents of my clipboard" in your environment.

```diff
diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
deleted file mode 100644
index db3bfcf..0000000
--- a/.github/workflows/checks.yml
+++ /dev/null
@@ -1,32 +0,0 @@
-name: wee-slack
-on:
-  push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
-
-jobs:
-  python:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        version: [2.7, 3.7]
-    steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.version }}
-    - name: Install dependencies
-      run: |
-        pip install pipenv
-        pipenv install --dev
-    - name: Lint with flake8
-      run: |
-        # stop the build if there are Python syntax errors or undefined names
-        pipenv run flake8 .
-        # exit-zero treats all errors as warnings.
-        pipenv run flake8 . --exit-zero --select=C,E,F,W
-    - name: Test with pytest
-      run: |
-        pipenv run pytest
diff --git a/.github/workflows/wee-slack.yml b/.github/workflows/wee-slack.yml
new file mode 100644
index 0000000..c0c61c7
--- /dev/null
+++ b/.github/workflows/wee-slack.yml
@@ -0,0 +1,53 @@
+name: wee-slack
+on:
+  push:
+    branches: [ master ]
+  pull_request:
+    branches: [ master ]
+
+strategy:
+  matrix:
+    python_version: [2.7, 3.7]
+
+jobs:
+  lint:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Set up Python (${{ matrix.python_version }})
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ matrix.python_version }}
+
+    - name: Install dependencies
+      run: |
+        pip install pipenv
+        pipenv install --dev --skip-lock
+
+    - name: Lint with Flake8
+      run: |
+        # stop the build if there are Python syntax errors or undefined names
+        pipenv run flake8 .
+
+        # exit-zero treats all errors as warnings.
+        pipenv run flake8 . --exit-zero --select=C,E,F,W
+
+  test:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Set up Python environment
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ matrix.python_version }}
+
+    - name: python/install-dependencies
+      run: |
+        pip install pipenv
+        pipenv install --dev --system
+
+    - name: python/test
+      run: |
+        pipenv run pytest
```

**Comment by sudoforge** [comment]
Updated the diff. I should note that due to the requirement to support python 2.7 and the inability to lock dependencies, it is possible that the jobs could install separate versions of dependencies.

**Comment by ashkulz** [comment]
Thanks, @sudoforge -- I wasn't able to get the cache to work and hence did it in a single job the same way Travis CI was set up.

**Comment by sudoforge** [comment]
@ashkulz what problems did you encounter when setting up the cache?

**Comment by ashkulz** [comment]
@sudoforge apparently `strategy` isn't allowed as a top-level configuration. Also, I don't really recall what the issue was -- I'm closing the PR as I think you'll come up with a better one :slightly_smiling_face:

**Pull request closed without merging**
