### PR TITLE
Add a command for opening an editor to compose a multiline message

### LINKED ISSUE #118: Send multiline messages
It would be awesome if there was a way to send multiline messages. According to the [slack API](https://api.slack.com/docs/formatting) this should be possibly by sending `\n` in the `text`, but it seems like before sending the message these get escaped to `\\n`. Any suggestions on how to make this work?

### PR DESCRIPTION
**Pull request by kattrali**
Borrows heavily from https://github.com/keith/edit-weechat

The current syntax is `/slack longmsg` but maybe there is a better name for the command. Also unsure how to keep the terms of edit-weechat's license.

Fixes #118

### CODE REVIEW

**Comment by keith** [comment]
Awesome!!! +1

**Comment by gilbertw1** [comment]
This is awesome! I've tested this out locally, and it works well. The one snag I'm seeing is that it's leaving behind lots of artifacts, requiring me to run ```/window refresh```.

It looks like you renamed the ```buf``` variable to ```current_buffer```, so I was able to fix it by replacing:

    ```weechat.command(buf, "/window refresh")```

with:

    ```weechat.command(current_buffer, "/window refresh")```

Also, it appears that the edit-weechat plugin is licensed under MIT, so there shouldn't be any issues there.

**Comment by kattrali** [comment]
@gilbertw1 Ah! You're correct. I renamed the variable a bit incompletely.

**Comment by oblitum** [comment]
Will this overcome https://github.com/weechat/weechat/issues/984??

**Comment by kattrali** [comment]
@oblitum yep!

**Comment by oblitum** [comment]
@kattrali cool!!

**Comment by oblitum** [comment]
@kattrali ah, this will be so awesome for code snippets! Much better than slack itself.

**Comment by oblitum** [comment]
@kattrali I don't know whether it's offtopic on this pull but I just recalled that I was about to request @keith to add the option of extending the edit command to accept the filetype, like `edit cpp` or `edit js`, what you think? I mean, this is for just opening the temporary file with a proper extension instead of `txt`, this avoid the need to call `:set ft js` for a `txt` file in Vim for example.

**Comment by oblitum** [comment]
Plus, for `/edit js`, etc, tripple backticks for code snippets could come implicit, around the temp file contents, so that it's not necessary to add them by hand.

**Comment by kattrali** [comment]
I think those are neat ideas, but maybe assume too much for general usage, @oblitum. If anything, I think that setting your editor command preference to something like `vim -c 'set syntax=markdown' -f` would make the most sense, as you can get syntax highlighting for nested code blocks (via `g:markdown_fenced_languages`) and also compose prose messages easily.

Unrelated, there should probably be a way to handle the case that sending the message fails - at minimum not deleting the cache file - though I'm not sure how to determine whether it worked yet.

**Comment by oblitum** [comment]
@kattrali thanks for your reponse. I don't like the markdown solution, I still have to enter backticks and I won't get real syntax highlighting and syntax checking as when I'd be coding in the actual programming language. That's what is most powerful for me, having Vim started for sending a code snippet and it doing syntax checking, etc, and I'd not even care for those tripple backticks. It doesn't take any generality of the feature because an filetype flag is necessary to behave this way, if it's not passed then it just behaves as it is currently, raw txt that requires the backticks.

**Comment by keith** [comment]
I think automatically backticks when entering this mode is making a pretty big assumption about how this is used. Even my general code usecase doesn't fit in this since I normally do something like:

    here's some block of code I want to share, what do you think:

    ```swift
    // the actual code
    ```

**Comment by oblitum** [comment]
@keith I didn't know slack accepted language specific code fences, if so, this could be made more handy by assuming the implicit fence is the same as the filetype.

**Comment by oblitum** [comment]
I see it may not be everyone's taste to reduce typing, having syntax check, etc, all automatically, I guess I'll have to fork the pull :)

**Comment by trygveaa** [comment]
I like the idea from @oblitum, and since it just adds an additional feature, I don't think it would be a problem in regards to general usage.

For the general usage that @kattrali mentioned, and the example @keith wrote, you would just do `/slack longmsg`, which acts like now. If you want @oblitum's feature you'd rather do e.g. `/slack longmsg js`. So both use cases are preserved.

**Comment by oblitum** [comment]
> @keith I didn't know slack accepted language specific code fences, if so, this could be made more handy by assuming the implicit fence is the same as the filetype.

I just tried and as far as I see, there's no support for language specific code fences in slack. Long thread here: https://twitter.com/slackhq/status/502238121493528576.

**Comment by keith** [comment]
The fencing mentioned is from the vim-markdown syntax plugin 


--
Keith Smiley

**Comment by oblitum** [comment]
@keith ah ok, I think you got me wrong. I don't want backticks in the openned buffer, it's assumed to be implicit, open a markdown buffer and using markdown fences was @kattrali suggestion.

**Comment by keith** [comment]
Right, but like I mentioned if they're implicit this command is only useful if you _only_ use it for code blocks. And you can't have any content in the message that is not part of the block. 


--
Keith Smiley

**Comment by oblitum** [comment]
Correct, and as @trygveaa said, nothing is lost, as it's behind a filetype flag.

**Comment by oblitum** [comment]
I'd rather change it to `/slack edit` too than `/slack longmsg`... :P

**Comment by kattrali** [comment]
This all sounds complicated compared to the initial problem - being able to type a multiline message, including long prose, bulleted lists, and code blocks. ¯\\\_(ツ)_/¯ Assuming everyone's editor is vim sounds like a stretch to begin with. If its a matter of having a syntax-checked buffer, once your editor is open, you can add a buffer with a given file type if you need those features, and copy things into the long message buffer as needed.

**Comment by trygveaa** [comment]
> Assuming everyone's editor is vim sounds like a stretch to begin with

The proposal isn't specific to vim. It just says to open a file with a specified suffix, which would give any editor the ability to do syntax highlighting, and then wrap it in back ticks.

I do agree that it's a bit more complicated though, but not much really. That might be a reason not to do it, at least until this PR is in.

**Comment by oblitum** [comment]
@kattrali I've created a competing pull with a screencast: https://github.com/wee-slack/wee-slack/pull/370. Also noticed that in that pull I've fixed an issue that's currently present in your pull, you must fix the `len` cheat at https://github.com/wee-slack/wee-slack/pull/365/files#diff-67e177ac444a14d6bcd7be6306ab4a20R2817 if you wish the if to pass when the channel is given.

**Comment by kattrali** [comment]
> I've fixed an issue that's currently present in your pull, you must fix the len check

Oh nice catch!

**Comment by Kareeeeem** [comment]
This works geat, added it to my setup. Hope it gets merged.

**Comment by oblitum** [comment]
@Kareeeeem have you tried the competing pull or even check the video? The increase in code in the other pull is completely negligible as well as the changes in the interface usage.

**Comment by Kareeeeem** [comment]
@oblitum. It looks very nice. But I am the odd ball that does not use syntax highlighting or autocomplete for real coding. Much less for quick snippets.

**Comment by oblitum** [comment]
> @oblitum. It looks very nice. But I am the odd ball that does not use syntax highlighting or autocomplete for real coding. Much less for quick snippets.

So you're only caring about your own workflow, which is covered by the other pull anyways, and solely based on that you wish others not having the feature that's not for real coding?

IMO, this request can be ignored.

**Comment by Kareeeeem** [comment]
I made no request, just expressed that *I* enjoy how this PR works as it is. That's all. 

Isn't this the place to express opinions about PRs?

**Comment by trygveaa** [comment]
Thanks for the PR, but we found a more general way of supporting multi line messages. That has been implemented with #430, and now that it's merged you should be able to use the [`edit.py`/edit-weechat](https://github.com/keith/edit-weechat) plugin for the same feature that this PR implements. Therefore, I'm closing this (see that PR for the reason that was merged instead of this). Please test it, and report back if something doesn't work, or if there's something from this PR that can't be done.

**Pull request closed without merging**
